services:
  app:
    image: shuralot/tracktest-app:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_SOCKET_URL=${NEXT_PUBLIC_SOCKET_URL}
    container_name: TrackTest
    restart: always
    expose:
      - "${APP_INTERNAL_PORT}"
    ports:
      - "${APP_PORT}:${APP_INTERNAL_PORT}"
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - EVOLUTION_API_URL=${EVOLUTION_API_URL}
      - EVOLUTION_API_KEY=${EVOLUTION_API_KEY}
      - EVOLUTION_INSTANCE_NAME=${EVOLUTION_INSTANCE_NAME}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - NODE_ENV=production
      - SOCKET_SERVER_URL=http://socket_server:${SOCKET_INTERNAL_PORT}
      - INTERNAL_API_KEY=${INTERNAL_API_KEY}
      - PORT=${APP_INTERNAL_PORT}
    # Em produção, não usamos volumes para o código, pois ele já está dentro da imagem.
    depends_on:
      - db
      - socket_server
    networks:
      - app_network

  socket_server:
    image: shuralot/tracktest-socket:latest
    build:
      context: ./socket-server
      dockerfile: Dockerfile
    container_name: socket_server
    restart: always
    expose:
      - "${SOCKET_INTERNAL_PORT}"
    ports:
      - "${SOCKET_PORT}:${SOCKET_INTERNAL_PORT}"
    environment:
      - PORT=${SOCKET_INTERNAL_PORT:-25040}
      - SOCKET_INTERNAL_PORT=${SOCKET_INTERNAL_PORT:-25040}
    networks:
      - app_network

  webhook-service:
    image: shuralot/tracktest-webhook:latest
    build:
      context: .
      dockerfile: ./webhook-service/Dockerfile
    container_name: webhook_service
    restart: always
    expose:
      - "${WEBHOOK_INTERNAL_PORT}"
    ports:
      - "${WEBHOOK_PORT}:${WEBHOOK_INTERNAL_PORT}"
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - MAIN_APP_URL=http://app:${APP_INTERNAL_PORT}
      - SOCKET_SERVER_URL=http://socket_server:${SOCKET_INTERNAL_PORT}
      - INTERNAL_API_KEY=${INTERNAL_API_KEY}
      - PORT=${WEBHOOK_INTERNAL_PORT:-25050}
      - WEBHOOK_INTERNAL_PORT=${WEBHOOK_INTERNAL_PORT:-25050}
    depends_on:
      - db
      - app
    networks:
      - app_network

  db:
    image: postgres:15-alpine
    container_name: TrackTest_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
